/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DotwellKnownAgentManifestRouteImport } from './routes/[.]well-known/agent-manifest'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPoliciesRouteImport } from './routes/_authenticated/policies'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as ApiPublicAgentManifestRouteImport } from './routes/api/public/agent-manifest'
import { Route as ApiPublicCatalogRouteImport } from './routes/api/public/catalog'
import { Route as ApiPublicQuoteRouteImport } from './routes/api/public/quote'
import { Route as ApiPublicSearchRouteImport } from './routes/api/public/search'
import { Route as ApiPublicProductsIdRouteImport } from './routes/api/public/products/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAgentManifestRoute =
  DotwellKnownAgentManifestRouteImport.update({
    id: '/.well-known/agent-manifest',
    path: '/.well-known/agent-manifest',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoliciesRoute = AuthenticatedPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicAgentManifestRoute = ApiPublicAgentManifestRouteImport.update({
  id: '/api/public/agent-manifest',
  path: '/api/public/agent-manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCatalogRoute = ApiPublicCatalogRouteImport.update({
  id: '/api/public/catalog',
  path: '/api/public/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuoteRoute = ApiPublicQuoteRouteImport.update({
  id: '/api/public/quote',
  path: '/api/public/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSearchRoute = ApiPublicSearchRouteImport.update({
  id: '/api/public/search',
  path: '/api/public/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductsIdRoute = ApiPublicProductsIdRouteImport.update({
  id: '/api/public/products/$id',
  path: '/api/public/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/.well-known/agent-manifest': typeof DotwellKnownAgentManifestRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/policies': typeof AuthenticatedPoliciesRoute
  '/products': typeof AuthenticatedProductsRoute
  '/api/public/agent-manifest': typeof ApiPublicAgentManifestRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/quote': typeof ApiPublicQuoteRoute
  '/api/public/search': typeof ApiPublicSearchRoute
  '/api/public/products/$id': typeof ApiPublicProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/.well-known/agent-manifest': typeof DotwellKnownAgentManifestRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/policies': typeof AuthenticatedPoliciesRoute
  '/products': typeof AuthenticatedProductsRoute
  '/api/public/agent-manifest': typeof ApiPublicAgentManifestRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/quote': typeof ApiPublicQuoteRoute
  '/api/public/search': typeof ApiPublicSearchRoute
  '/api/public/products/$id': typeof ApiPublicProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/.well-known/agent-manifest': typeof DotwellKnownAgentManifestRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/policies': typeof AuthenticatedPoliciesRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/api/public/agent-manifest': typeof ApiPublicAgentManifestRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/quote': typeof ApiPublicQuoteRoute
  '/api/public/search': typeof ApiPublicSearchRoute
  '/api/public/products/$id': typeof ApiPublicProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/.well-known/agent-manifest'
    | '/dashboard'
    | '/policies'
    | '/products'
    | '/api/public/agent-manifest'
    | '/api/public/catalog'
    | '/api/public/quote'
    | '/api/public/search'
    | '/api/public/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/.well-known/agent-manifest'
    | '/dashboard'
    | '/policies'
    | '/products'
    | '/api/public/agent-manifest'
    | '/api/public/catalog'
    | '/api/public/quote'
    | '/api/public/search'
    | '/api/public/products/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/.well-known/agent-manifest'
    | '/_authenticated/dashboard'
    | '/_authenticated/policies'
    | '/_authenticated/products'
    | '/api/public/agent-manifest'
    | '/api/public/catalog'
    | '/api/public/quote'
    | '/api/public/search'
    | '/api/public/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  DotwellKnownAgentManifestRoute: typeof DotwellKnownAgentManifestRoute
  ApiPublicAgentManifestRoute: typeof ApiPublicAgentManifestRoute
  ApiPublicCatalogRoute: typeof ApiPublicCatalogRoute
  ApiPublicQuoteRoute: typeof ApiPublicQuoteRoute
  ApiPublicSearchRoute: typeof ApiPublicSearchRoute
  ApiPublicProductsIdRoute: typeof ApiPublicProductsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-manifest': {
      id: '/.well-known/agent-manifest'
      path: '/.well-known/agent-manifest'
      fullPath: '/.well-known/agent-manifest'
      preLoaderRoute: typeof DotwellKnownAgentManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/policies': {
      id: '/_authenticated/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AuthenticatedPoliciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/agent-manifest': {
      id: '/api/public/agent-manifest'
      path: '/api/public/agent-manifest'
      fullPath: '/api/public/agent-manifest'
      preLoaderRoute: typeof ApiPublicAgentManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/catalog': {
      id: '/api/public/catalog'
      path: '/api/public/catalog'
      fullPath: '/api/public/catalog'
      preLoaderRoute: typeof ApiPublicCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/quote': {
      id: '/api/public/quote'
      path: '/api/public/quote'
      fullPath: '/api/public/quote'
      preLoaderRoute: typeof ApiPublicQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/search': {
      id: '/api/public/search'
      path: '/api/public/search'
      fullPath: '/api/public/search'
      preLoaderRoute: typeof ApiPublicSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/products/$id': {
      id: '/api/public/products/$id'
      path: '/api/public/products/$id'
      fullPath: '/api/public/products/$id'
      preLoaderRoute: typeof ApiPublicProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPoliciesRoute: typeof AuthenticatedPoliciesRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPoliciesRoute: AuthenticatedPoliciesRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  DotwellKnownAgentManifestRoute: DotwellKnownAgentManifestRoute,
  ApiPublicAgentManifestRoute: ApiPublicAgentManifestRoute,
  ApiPublicCatalogRoute: ApiPublicCatalogRoute,
  ApiPublicQuoteRoute: ApiPublicQuoteRoute,
  ApiPublicSearchRoute: ApiPublicSearchRoute,
  ApiPublicProductsIdRoute: ApiPublicProductsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
