/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AgentApiRouteImport } from './routes/agent-api'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DotwellKnownAgentManifestRouteImport } from './routes/[.]well-known/agent-manifest'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedBuyerRouteImport } from './routes/_authenticated/buyer'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedJudgeRouteImport } from './routes/_authenticated/judge'
import { Route as AuthenticatedPoliciesRouteImport } from './routes/_authenticated/policies'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as ApiAgentBuyerRouteImport } from './routes/api/agent/buyer'
import { Route as ApiAgentExternalBuyerRouteImport } from './routes/api/agent/external-buyer'
import { Route as ApiPublicAgentManifestRouteImport } from './routes/api/public/agent-manifest'
import { Route as ApiPublicCatalogRouteImport } from './routes/api/public/catalog'
import { Route as ApiPublicCheckoutRouteImport } from './routes/api/public/checkout'
import { Route as ApiPublicNegotiateRouteImport } from './routes/api/public/negotiate'
import { Route as ApiPublicQuoteRouteImport } from './routes/api/public/quote'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as ApiPublicSearchRouteImport } from './routes/api/public/search'
import { Route as ApiPublicOrdersIdRouteImport } from './routes/api/public/orders/$id'
import { Route as ApiPublicProductsIdRouteImport } from './routes/api/public/products/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentApiRoute = AgentApiRouteImport.update({
  id: '/agent-api',
  path: '/agent-api',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAgentManifestRoute =
  DotwellKnownAgentManifestRouteImport.update({
    id: '/.well-known/agent-manifest',
    path: '/.well-known/agent-manifest',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuyerRoute = AuthenticatedBuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJudgeRoute = AuthenticatedJudgeRouteImport.update({
  id: '/judge',
  path: '/judge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoliciesRoute = AuthenticatedPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAgentBuyerRoute = ApiAgentBuyerRouteImport.update({
  id: '/api/agent/buyer',
  path: '/api/agent/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentExternalBuyerRoute = ApiAgentExternalBuyerRouteImport.update({
  id: '/api/agent/external-buyer',
  path: '/api/agent/external-buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentManifestRoute = ApiPublicAgentManifestRouteImport.update({
  id: '/api/public/agent-manifest',
  path: '/api/public/agent-manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCatalogRoute = ApiPublicCatalogRouteImport.update({
  id: '/api/public/catalog',
  path: '/api/public/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckoutRoute = ApiPublicCheckoutRouteImport.update({
  id: '/api/public/checkout',
  path: '/api/public/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNegotiateRoute = ApiPublicNegotiateRouteImport.update({
  id: '/api/public/negotiate',
  path: '/api/public/negotiate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuoteRoute = ApiPublicQuoteRouteImport.update({
  id: '/api/public/quote',
  path: '/api/public/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSearchRoute = ApiPublicSearchRouteImport.update({
  id: '/api/public/search',
  path: '/api/public/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrdersIdRoute = ApiPublicOrdersIdRouteImport.update({
  id: '/api/public/orders/$id',
  path: '/api/public/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductsIdRoute = ApiPublicProductsIdRouteImport.update({
  id: '/api/public/products/$id',
  path: '/api/public/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-api': typeof AgentApiRoute
  '/login': typeof LoginRoute
  '/.well-known/agent-manifest': typeof DotwellKnownAgentManifestRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/buyer': typeof AuthenticatedBuyerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/judge': typeof AuthenticatedJudgeRoute
  '/policies': typeof AuthenticatedPoliciesRoute
  '/products': typeof AuthenticatedProductsRoute
  '/api/agent/buyer': typeof ApiAgentBuyerRoute
  '/api/agent/external-buyer': typeof ApiAgentExternalBuyerRoute
  '/api/public/agent-manifest': typeof ApiPublicAgentManifestRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/negotiate': typeof ApiPublicNegotiateRoute
  '/api/public/quote': typeof ApiPublicQuoteRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/search': typeof ApiPublicSearchRoute
  '/api/public/orders/$id': typeof ApiPublicOrdersIdRoute
  '/api/public/products/$id': typeof ApiPublicProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-api': typeof AgentApiRoute
  '/login': typeof LoginRoute
  '/.well-known/agent-manifest': typeof DotwellKnownAgentManifestRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/buyer': typeof AuthenticatedBuyerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/judge': typeof AuthenticatedJudgeRoute
  '/policies': typeof AuthenticatedPoliciesRoute
  '/products': typeof AuthenticatedProductsRoute
  '/api/agent/buyer': typeof ApiAgentBuyerRoute
  '/api/agent/external-buyer': typeof ApiAgentExternalBuyerRoute
  '/api/public/agent-manifest': typeof ApiPublicAgentManifestRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/negotiate': typeof ApiPublicNegotiateRoute
  '/api/public/quote': typeof ApiPublicQuoteRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/search': typeof ApiPublicSearchRoute
  '/api/public/orders/$id': typeof ApiPublicOrdersIdRoute
  '/api/public/products/$id': typeof ApiPublicProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agent-api': typeof AgentApiRoute
  '/login': typeof LoginRoute
  '/.well-known/agent-manifest': typeof DotwellKnownAgentManifestRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/buyer': typeof AuthenticatedBuyerRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/judge': typeof AuthenticatedJudgeRoute
  '/_authenticated/policies': typeof AuthenticatedPoliciesRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/api/agent/buyer': typeof ApiAgentBuyerRoute
  '/api/agent/external-buyer': typeof ApiAgentExternalBuyerRoute
  '/api/public/agent-manifest': typeof ApiPublicAgentManifestRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/negotiate': typeof ApiPublicNegotiateRoute
  '/api/public/quote': typeof ApiPublicQuoteRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/search': typeof ApiPublicSearchRoute
  '/api/public/orders/$id': typeof ApiPublicOrdersIdRoute
  '/api/public/products/$id': typeof ApiPublicProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-api'
    | '/login'
    | '/.well-known/agent-manifest'
    | '/approvals'
    | '/buyer'
    | '/dashboard'
    | '/judge'
    | '/policies'
    | '/products'
    | '/api/agent/buyer'
    | '/api/agent/external-buyer'
    | '/api/public/agent-manifest'
    | '/api/public/catalog'
    | '/api/public/checkout'
    | '/api/public/negotiate'
    | '/api/public/quote'
    | '/api/public/razorpay-webhook'
    | '/api/public/search'
    | '/api/public/orders/$id'
    | '/api/public/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-api'
    | '/login'
    | '/.well-known/agent-manifest'
    | '/approvals'
    | '/buyer'
    | '/dashboard'
    | '/judge'
    | '/policies'
    | '/products'
    | '/api/agent/buyer'
    | '/api/agent/external-buyer'
    | '/api/public/agent-manifest'
    | '/api/public/catalog'
    | '/api/public/checkout'
    | '/api/public/negotiate'
    | '/api/public/quote'
    | '/api/public/razorpay-webhook'
    | '/api/public/search'
    | '/api/public/orders/$id'
    | '/api/public/products/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agent-api'
    | '/login'
    | '/.well-known/agent-manifest'
    | '/_authenticated/approvals'
    | '/_authenticated/buyer'
    | '/_authenticated/dashboard'
    | '/_authenticated/judge'
    | '/_authenticated/policies'
    | '/_authenticated/products'
    | '/api/agent/buyer'
    | '/api/agent/external-buyer'
    | '/api/public/agent-manifest'
    | '/api/public/catalog'
    | '/api/public/checkout'
    | '/api/public/negotiate'
    | '/api/public/quote'
    | '/api/public/razorpay-webhook'
    | '/api/public/search'
    | '/api/public/orders/$id'
    | '/api/public/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgentApiRoute: typeof AgentApiRoute
  LoginRoute: typeof LoginRoute
  DotwellKnownAgentManifestRoute: typeof DotwellKnownAgentManifestRoute
  ApiAgentBuyerRoute: typeof ApiAgentBuyerRoute
  ApiAgentExternalBuyerRoute: typeof ApiAgentExternalBuyerRoute
  ApiPublicAgentManifestRoute: typeof ApiPublicAgentManifestRoute
  ApiPublicCatalogRoute: typeof ApiPublicCatalogRoute
  ApiPublicCheckoutRoute: typeof ApiPublicCheckoutRoute
  ApiPublicNegotiateRoute: typeof ApiPublicNegotiateRoute
  ApiPublicQuoteRoute: typeof ApiPublicQuoteRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiPublicSearchRoute: typeof ApiPublicSearchRoute
  ApiPublicOrdersIdRoute: typeof ApiPublicOrdersIdRoute
  ApiPublicProductsIdRoute: typeof ApiPublicProductsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-api': {
      id: '/agent-api'
      path: '/agent-api'
      fullPath: '/agent-api'
      preLoaderRoute: typeof AgentApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-manifest': {
      id: '/.well-known/agent-manifest'
      path: '/.well-known/agent-manifest'
      fullPath: '/.well-known/agent-manifest'
      preLoaderRoute: typeof DotwellKnownAgentManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buyer': {
      id: '/_authenticated/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof AuthenticatedBuyerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/judge': {
      id: '/_authenticated/judge'
      path: '/judge'
      fullPath: '/judge'
      preLoaderRoute: typeof AuthenticatedJudgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/policies': {
      id: '/_authenticated/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AuthenticatedPoliciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/agent/buyer': {
      id: '/api/agent/buyer'
      path: '/api/agent/buyer'
      fullPath: '/api/agent/buyer'
      preLoaderRoute: typeof ApiAgentBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/external-buyer': {
      id: '/api/agent/external-buyer'
      path: '/api/agent/external-buyer'
      fullPath: '/api/agent/external-buyer'
      preLoaderRoute: typeof ApiAgentExternalBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-manifest': {
      id: '/api/public/agent-manifest'
      path: '/api/public/agent-manifest'
      fullPath: '/api/public/agent-manifest'
      preLoaderRoute: typeof ApiPublicAgentManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/catalog': {
      id: '/api/public/catalog'
      path: '/api/public/catalog'
      fullPath: '/api/public/catalog'
      preLoaderRoute: typeof ApiPublicCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/checkout': {
      id: '/api/public/checkout'
      path: '/api/public/checkout'
      fullPath: '/api/public/checkout'
      preLoaderRoute: typeof ApiPublicCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/negotiate': {
      id: '/api/public/negotiate'
      path: '/api/public/negotiate'
      fullPath: '/api/public/negotiate'
      preLoaderRoute: typeof ApiPublicNegotiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/quote': {
      id: '/api/public/quote'
      path: '/api/public/quote'
      fullPath: '/api/public/quote'
      preLoaderRoute: typeof ApiPublicQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/search': {
      id: '/api/public/search'
      path: '/api/public/search'
      fullPath: '/api/public/search'
      preLoaderRoute: typeof ApiPublicSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/orders/$id': {
      id: '/api/public/orders/$id'
      path: '/api/public/orders/$id'
      fullPath: '/api/public/orders/$id'
      preLoaderRoute: typeof ApiPublicOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/products/$id': {
      id: '/api/public/products/$id'
      path: '/api/public/products/$id'
      fullPath: '/api/public/products/$id'
      preLoaderRoute: typeof ApiPublicProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedBuyerRoute: typeof AuthenticatedBuyerRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedJudgeRoute: typeof AuthenticatedJudgeRoute
  AuthenticatedPoliciesRoute: typeof AuthenticatedPoliciesRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedBuyerRoute: AuthenticatedBuyerRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedJudgeRoute: AuthenticatedJudgeRoute,
  AuthenticatedPoliciesRoute: AuthenticatedPoliciesRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgentApiRoute: AgentApiRoute,
  LoginRoute: LoginRoute,
  DotwellKnownAgentManifestRoute: DotwellKnownAgentManifestRoute,
  ApiAgentBuyerRoute: ApiAgentBuyerRoute,
  ApiAgentExternalBuyerRoute: ApiAgentExternalBuyerRoute,
  ApiPublicAgentManifestRoute: ApiPublicAgentManifestRoute,
  ApiPublicCatalogRoute: ApiPublicCatalogRoute,
  ApiPublicCheckoutRoute: ApiPublicCheckoutRoute,
  ApiPublicNegotiateRoute: ApiPublicNegotiateRoute,
  ApiPublicQuoteRoute: ApiPublicQuoteRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiPublicSearchRoute: ApiPublicSearchRoute,
  ApiPublicOrdersIdRoute: ApiPublicOrdersIdRoute,
  ApiPublicProductsIdRoute: ApiPublicProductsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
